create view v2
 as
select top 100  PERCENT O.DATE AS '日期'
,OH.P_CLOSE AS '期貨'
,(OH.P_CLOSE-LAG(OH.P_CLOSE) OVER (ORDER BY OH.DATE)) AS '期貨差額'
,ROUND((OH.P_CLOSE-(select TWSE_CLOSE_PRICE from PROD_TWSE_DATA where DATE=O.DATE)),3) as '期現價差'
,ROUND((select F_BQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_BQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE),0) AS '外資多單'
, ROUND(((select F_BQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_BQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)
	-LAG((select F_BQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_BQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)) 
	 OVER (ORDER BY O.DATE)),0) AS '外資多單差額'

,ROUND((select F_SQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_SQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE),0) AS '外資空單'

,ROUND(((select F_SQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_SQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)
	-LAG((select F_SQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_SQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)) 
	 OVER (ORDER BY O.DATE)),0) AS '外資空單差額'

 ,ROUND((select F_BQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_BQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)
	-(select F_SQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	-(select F_SQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE),0) AS '餘額'

 ,ROUND((((select F_BQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_BQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)
	-(select F_SQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	-(select F_SQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE))-LAG(((select F_BQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	+(select F_BQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE)
	-(select F_SQTY_TOTAL from PROD_FUTUER_DTAT where SYMBOLNAME ='TXF' and ID = 3  and DATE=O.DATE)
	-(select F_SQTY_TOTAL/4 from PROD_FUTUER_DTAT where SYMBOLNAME ='MXF' and ID = 3  and DATE=O.DATE))) 
	OVER (ORDER BY O.DATE)),0) AS '餘額差額'


,OP_CALL_BQTY_TOTAL AS '買權多單'
,(OP_CALL_BQTY_TOTAL-LAG(OP_CALL_BQTY_TOTAL) OVER (ORDER BY O.DATE)) AS '買權多單差額'
,OP_CALL_SQTY_TOTAL AS '買權空單'
,(OP_CALL_SQTY_TOTAL-LAG(OP_CALL_SQTY_TOTAL) OVER (ORDER BY O.DATE)) AS '買權空單差額'
,(OP_CALL_BQTY_TOTAL-OP_CALL_SQTY_TOTAL) AS '買權淨額'
,((OP_CALL_BQTY_TOTAL-OP_CALL_SQTY_TOTAL)-LAG((OP_CALL_BQTY_TOTAL-OP_CALL_SQTY_TOTAL)) OVER (ORDER BY O.DATE)) AS '買權淨額差額'
,OP_PUT_BQTY_TOTAL AS '賣權多單'
,(OP_PUT_BQTY_TOTAL-LAG(OP_PUT_BQTY_TOTAL) OVER (ORDER BY O.DATE)) AS '賣權多單差額'
,OP_PUT_SQTY_TOTAL AS '賣權空單'
,(OP_PUT_SQTY_TOTAL-LAG(OP_PUT_SQTY_TOTAL) OVER (ORDER BY O.DATE)) AS '賣權空單差額'
,(OP_PUT_BQTY_TOTAL-OP_PUT_SQTY_TOTAL) AS '賣權淨額'
,((OP_PUT_BQTY_TOTAL-OP_PUT_SQTY_TOTAL)-LAG((OP_PUT_BQTY_TOTAL-OP_PUT_SQTY_TOTAL)) OVER (ORDER BY O.DATE)) AS '賣權淨額差額'
,((OP_CALL_BQTY_TOTAL-OP_CALL_SQTY_TOTAL)-(OP_PUT_BQTY_TOTAL-OP_PUT_SQTY_TOTAL)) AS '選擇權部位淨多空'
,(((OP_CALL_BQTY_TOTAL-OP_CALL_SQTY_TOTAL)-(OP_PUT_BQTY_TOTAL-OP_PUT_SQTY_TOTAL))-LAG(((OP_CALL_BQTY_TOTAL-OP_CALL_SQTY_TOTAL)-(OP_PUT_BQTY_TOTAL-OP_PUT_SQTY_TOTAL))) OVER (ORDER BY O.DATE)) AS '選擇權部位差額'
 
from PROD_OP_DTAT O
join PROD_OHLCV OH
on O.DATE=OH.DATE
where O.ID =3 and O.SYMBOLNAME='TXO'and OH.SYMBOLNAME = 'TXF'
order by O.DATE desc

go