  CREATE VIEW v1
 as
 select top 100 PERCENT
  P.DATE AS '日期'
 ,P_OPEN AS '開'
 ,P_HIGH AS '高'
 ,P_LOW AS '低'
 ,P_CLOSE AS '收'
 ,VOLUME AS '成交量'
 ,O_VOLUME AS '未成交量'
 ,P_OPEN-P_CLOSE AS '開盤價差'
 ,(P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) AS '漲跌'
 ,(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) AS '量差'
 ,(O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) AS '未平倉差'

 ,CASE 
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) > 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) > 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) > 0 THEN '多頭穩健'
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) < 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) > 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) > 0 THEN '空頭回補，弱勢反彈'	
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) > 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) > 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) < 0 THEN '多方強勢' 		         
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) < 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) > 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) < 0 THEN '多頭走勢即將進入尾聲' 		
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) > 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) < 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) > 0 THEN '空頭穩健' 
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) < 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) < 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) > 0 THEN '多頭平倉，強勢整理' 		 
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) > 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) < 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) < 0 THEN '空方強勢' 
	WHEN (O_VOLUME-LAG(O_VOLUME) OVER (ORDER BY P.DATE)) < 0	and	(VOLUME-LAG(VOLUME) OVER (ORDER BY P.DATE)) < 0	and (P_CLOSE-LAG(P_CLOSE) OVER (ORDER BY P.DATE)) < 0 THEN '空頭走勢即將進入尾聲' 
        ELSE 'NULL' END '判斷'

 ,round((select (BUY_AMT-SELL_AMT)/100000000 from  PROD_TWSE_THREE_CORP_DATA where ID =1 and DATE=P.DATE),4) AS '自營'
 ,round((select (BUY_AMT-SELL_AMT)/100000000 from  PROD_TWSE_THREE_CORP_DATA where ID =2 and DATE=P.DATE),4) AS '投信'
 ,round((select (BUY_AMT-SELL_AMT)/100000000 from  PROD_TWSE_THREE_CORP_DATA where ID =3 and DATE=P.DATE),4) AS '外資'

 ,round(((select (BUY_AMT-SELL_AMT)/100000000 from  PROD_TWSE_THREE_CORP_DATA where ID =1 and DATE=P.DATE)
 +(select (BUY_AMT-SELL_AMT)/100000000 from  PROD_TWSE_THREE_CORP_DATA where ID =2 and DATE=P.DATE)
 +(select (BUY_AMT-SELL_AMT)/100000000 from  PROD_TWSE_THREE_CORP_DATA where ID =3 and DATE=P.DATE)),4) AS '合計'

 ,(select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='LEND_QTY' and DATE=P.DATE)  AS '融資'
 ,((select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='LEND_QTY' and DATE=P.DATE)	 
   -LAG((select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='LEND_QTY' and DATE=P.DATE))	 
	OVER (ORDER BY P.DATE)) AS '融資增減(張)'

 ,(select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='BORROW_QTY' and DATE=P.DATE)  AS '融券'
 ,((select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='BORROW_QTY' and DATE=P.DATE)	 
   -LAG((select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='BORROW_QTY' and DATE=P.DATE))	 
	OVER (ORDER BY P.DATE)) AS '融券增減(張)'

 ,(select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='LEND_AMT' and DATE=P.DATE)  AS '融券餘額'
 ,round((((select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='LEND_AMT' and DATE=P.DATE)	 
   -LAG((select N_BALANCE from PROD_STOCK_LEND_BORROW where SYMBOLNAME ='LEND_AMT' and DATE=P.DATE))	 
	OVER (ORDER BY P.DATE))/100000),2) AS '融資餘額(億)'

from PROD_OHLCV P 
where SYMBOLNAME = 'TXF'
order by P.DATE desc
 
 go
 
        

 
 
 